### ISSUE TITLE
Feature Request: different color hostname for SSH sessions

### ISSUE THREAD

**Issue by emansom** [badouralix/oh-my-via#12]
It'd be a nice to have if hostname would be colored (e.g. green) when the session is an active SSH session.

**Comment by badouralix** [comment]
Thanks for the suggestion @emansom, this should be fairly doable !

**Comment by badouralix** [comment]
With [v1.3.0](https://github.com/badouralix/oh-my-via/releases/tag/v1.3.0) you can now set independently `OHMYVIA_CONTEXT_HOSTNAME_COLOR` ( color used for a local session ) and `OHMYVIA_CONTEXT_HOSTNAME_COLOR_SSH` ( color used for a session over ssh )

**Comment by emansom** [comment]
Thanks for implementing! Applaud the quick turnaround 😌
