### ISSUE TITLE
How to show just the current directory instead of entire path

### ISSUE THREAD

**Issue by samuel-cavalcanti** [badouralix/oh-my-via#2]
Hey @badouralix ,
Wondering where I can make a change to just show the current directory instead of the entire path?

**Comment by samuel-cavalcanti** [comment]
i got !!  
changing  oh-my-via/functions/prompt_utils.zsh
 prompt_dir () {
	local current_dir="$OHMYVIA_DIR_COLOR%c%b%f"

	echo $current_dir
}
:)

**Comment by badouralix** [comment]
Yep that works ! I think we can even make it a bit more generic using `%1~` instead of `%c`

**Comment by samuel-cavalcanti** [comment]
what is the difference ?

**Comment by badouralix** [comment]
None but then it's configurable with an environment variable instead of patching the code. I'm writing the generic patch

**Comment by samuel-cavalcanti** [comment]
Ok I'll change now

**Comment by samuel-cavalcanti** [comment]
Ok I'll change

**Comment by badouralix** [comment]
With [v1.1.0](https://github.com/badouralix/oh-my-via/releases/tag/v1.1.0) you can now specify in your `zshrc`:

```zsh
export OHMYVIA_DIR_SIZE=1
```
